### ISSUE TITLE
Transaction Fees Not Calculated Correctly in Certain Cases

### ISSUE THREAD

**Issue by raindust** [soonlabs/igloo#12]
This issue typically occurs in the following scenarios:
- Executing multiple transactions as a batch in the SVM
- Creating a new slot based on existing slots or reopening storage

The issue can be observed in the `storage_basic_process_works` and `reorg_works` unit tests, which are marked with `FIXME` and `TODO`.

**Comment by MichaelTang23** [comment]
Bob is the leader of previous slot, so he has the 50% tx fee of that slot, should take that into consideration.
